apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: usersdb
            - name: MYSQL_USER
              value: appuser
            - name: MYSQL_PASSWORD
              value: appuser
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql  # MySQL data directory
      volumes:                    # volumes field should be inside the "spec" of the template
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
